togglz:
  features:
    NEW_PRODUCT:
      enabled: false
  features-file: 'file:./feature.properties'
  console:
    secured: false

management:
  endpoints:
    web:
      exposure:
        include: 'togglz'
spring:
  profiles:
    active: dev
